import { db } from "./index";
import { vendorsTable, productsTable } from "./schema";

async function seed() {
  console.log("Seeding vendors...");

  await db.delete(productsTable);
  await db.delete(vendorsTable);

  const vendors = await db
    .insert(vendorsTable)
    .values([
      {
        name: "Bellini Baking Co.",
        contactName: "Maria Bellini",
        email: "maria@bellinibaking.com",
        description:
          "Stone-oven sourdoughs, focaccia, and seasonal pastries baked in small batches every Wednesday night for Thursday market. Each loaf is made with heritage grain and a 48-hour cold ferment.",
        location: "Melrose, MA",
        website: "https://www.bellinibakingco.com/",
        instagram: "@bellinibakingco",
        launchMode: "reserve_for_pickup",
        status: "live",
        marketDates: "Thursday, June 18",
        pickupInstructions: "Pick up at the vendor tent by showing your confirmation email.",
      },
      {
        name: "Del Sur Empanadas",
        contactName: "Carlos & Ana Suarez",
        email: "hola@delsurempanadas.com",
        description:
          "Argentinian and Chilean-inspired empanadas made with all-natural ingredients and baked, never fried. Frozen 6-packs ready to take home and bake. Born in Reading, MA.",
        location: "Stoneham, MA",
        website: "https://delsurnatural.com",
        instagram: "@delsurempanadas",
        launchMode: "reserve_for_pickup",
        status: "live",
        marketDates: "Thursday, June 18",
        pickupInstructions: "Pick up at the vendor tent by showing your confirmation email.",
      },
      {
        name: "Wilmington Honey Bee",
        contactName: "James Alvarez",
        email: "james@wilmingtonhoneybee.com",
        description:
          "Locally harvested raw honey from hives maintained in Wilmington. Raw, unfiltered, and available in 8oz and 1lb sizes.",
        location: "Wilmington, MA",
        website: "https://wilmingtonhoneybee.com",
        instagram: "@Wilmington_honey_bee",
        launchMode: "reserve_for_pickup",
        status: "live",
        marketDates: "Thursday, June 18",
        pickupInstructions: "Pick up at the vendor tent by showing your confirmation email.",
      },
      {
        name: "Crave Creations",
        contactName: "Sophie Chen",
        email: "sophie@cravecreations.com",
        description:
          "Customizable dessert and snack bar bringing curated indulgence to the market. Choose from waffle sticks, mini pancakes, mini cakes, and lemonades — then build your plate with toppings like fresh fruit, Biscoff crumble, and Oreo, plus sauces from chocolate to salted caramel.",
        location: "Winchester, MA",
        instagram: "@cravecreations_ma",
        launchMode: "featured_products",
        status: "live",
        marketDates: "Thursday, June 18",
      },
      {
        name: "Spice Weasel Sauce",
        contactName: "Tom Nguyen",
        email: "tom@spiceweasel.com",
        description:
          "Small-batch hot sauces, salsa, hot honey, and seasoning salt crafted in Beverly, MA from handpicked, homegrown peppers. Inspired by the momo sauces of Sikkim, India.",
        location: "Beverly, MA",
        website: "https://spiceweaselsauce.com",
        instagram: "@spiceweaselsauce",
        launchMode: "reserve_for_pickup",
        status: "live",
        marketDates: "Thursday, June 18",
        pickupInstructions: "Pick up at the vendor tent by showing your confirmation email.",
      },
      {
        name: "Teresa's Farm",
        contactName: "Teresa Novak",
        website: "https://teresa-farm.com",
        description:
          "Fresh-baked goods, handmade jams, and farm-to-table specialties made in small batches in Boxford, MA. Tarts, braided loaves, Danish, focaccia, and rotating seasonal jams at every market.",
        location: "Boxford, MA",
        launchMode: "featured_products",
        status: "live",
        marketDates: "Thursday, June 18",
      },
      {
        name: "Riverdale Farm",
        contactName: "Ed and Pat Rivera",
        description:
          "Family farm growing over 200 acres in Groton, MA. Seasonal produce including strawberries, broccoli, peppers, eggplant, lettuce, cabbage, and root vegetables — harvested fresh for each market.",
        location: "Groton, MA",
        launchMode: "reserve_for_pickup",
        status: "live",
        marketDates: "Thursday, June 18",
      },
      {
        name: "Aaronap Cellars",
        contactName: "Aaron Parker",
        description:
          "Estate-grown wines from a working vineyard in Stoneham's western hills. Dry whites, rosés, and a signature semi-sweet apple-grape blend made from heritage orchard fruit.",
        location: "Stoneham, MA",
        website: "https://aaronapcellars.com",
        instagram: "@aaronapcellars",
        launchMode: "profile_only",
        status: "live",
        marketDates: "Thursday, June 18",
      },
    ])
    .returning();

  console.log(`Inserted ${vendors.length} vendors.`);

  const vendorMap = Object.fromEntries(vendors.map((v) => [v.name, v.id]));

  const products = await db
    .insert(productsTable)
    .values([
      // Bellini Baking Co.
      {
        vendorId: vendorMap["Bellini Baking Co."],
        name: "Country Sourdough Loaf",
        description: "Heritage wheat, sea salt, and 48-hour cold ferment. One 1.5lb loaf.",
        price: "$10",
        reservationAllowed: true,
        maxPerReservation: 3,
        quantityAvailable: 30,
        status: "live",
      },
      {
        vendorId: vendorMap["Bellini Baking Co."],
        name: "Rosemary Focaccia",
        description: "Olive oil, sea salt, fresh rosemary. Full sheet serves 6–8.",
        price: "$12",
        reservationAllowed: true,
        maxPerReservation: 2,
        quantityAvailable: 15,
        status: "live",
      },
      {
        vendorId: vendorMap["Bellini Baking Co."],
        name: "Seasonal Pastry Box",
        description: "Assorted pastries baked the morning of market day. Contents change weekly.",
        price: "$14",
        reservationAllowed: true,
        maxPerReservation: 2,
        quantityAvailable: 20,
        status: "live",
      },
      // Del Sur Empanadas
      {
        vendorId: vendorMap["Del Sur Empanadas"],
        name: "Fabiola's Traditional Beef (6-pack)",
        description: "Classic Argentine-style beef empanadas — ground beef, onions, hard-boiled eggs, and raisins. All-natural, baked not fried. Frozen, ready to bake at home. Dairy free.",
        price: "$16",
        imageUrl: "https://133739804.cdn6.editmysite.com/uploads/1/3/3/7/133739804/ATJY4UCEEU22SZEW2HT5LJN2.jpeg",
        allergenNote: "Contains: wheat, eggs. Dairy free.",
        reservationAllowed: true,
        maxPerReservation: 3,
        quantityAvailable: 40,
        status: "live",
      },
      {
        vendorId: vendorMap["Del Sur Empanadas"],
        name: "NMC: New Mexico Chicken (6-pack)",
        description: "Chicken breast with lime juice, roasted poblano peppers, sofrito, cheddar cheese, and corn. All-natural, baked not fried. Frozen, ready to bake at home.",
        price: "$15",
        imageUrl: "https://133739804.cdn6.editmysite.com/uploads/1/3/3/7/133739804/Y67ZCJNVMJNWS2GATUNJZLDO.jpeg",
        allergenNote: "Contains: wheat, milk.",
        reservationAllowed: true,
        maxPerReservation: 3,
        quantityAvailable: 30,
        status: "live",
      },
      // Wilmington Honey Bee
      {
        vendorId: vendorMap["Wilmington Honey Bee"],
        name: "Artisan Fall Raw Honey",
        description: "All natural locally sourced honey. Available in 8oz ($8.00) and 1lb ($15.00).",
        price: "$8.00",
        imageUrl: "https://wilmingtonhoneybee.com/wp-content/uploads/2024/01/8oz-fall-honey-scaled.jpg",
        reservationAllowed: true,
        maxPerReservation: 4,
        quantityAvailable: 30,
        status: "live",
      },
      {
        vendorId: vendorMap["Wilmington Honey Bee"],
        name: "Artisan Spring Raw Honey",
        description: "All natural locally sourced honey. Available in 8oz ($8.00) and 1lb ($15.00).",
        price: "$8.00",
        imageUrl: "https://wilmingtonhoneybee.com/wp-content/uploads/2024/01/8oz-Spring-Honey-scaled.jpg",
        reservationAllowed: true,
        maxPerReservation: 4,
        quantityAvailable: 30,
        status: "live",
      },
      // Crave Creations
      {
        vendorId: vendorMap["Crave Creations"],
        name: "Waffle Sticks",
        description: "Crispy Belgian waffle sticks with up to 3 toppings and 1 sauce. Toppings: sprinkles, Fruity Pebbles, Oreo crumble, banana, strawberry, Biscoff crumble, whipped cream. Sauces: chocolate, strawberry, salted caramel, pistachio, white chocolate, maple syrup. Extra toppings $0.25 each.",
        price: "$9 ea. | 2 for $15",
        imageUrl: "/images/crave-waffle-sticks.jpg",
        reservationAllowed: false,
        status: "live",
      },
      {
        vendorId: vendorMap["Crave Creations"],
        name: "Mini Pancakes",
        description: "Bite-sized fluffy mini pancakes with your choice of toppings and sauces. Order 10 minis for $7 or go big with 15 for $11.",
        price: "10 for $7 | 15 for $11",
        imageUrl: "/images/crave-mini-pancakes.jpg",
        reservationAllowed: false,
        status: "live",
      },
      {
        vendorId: vendorMap["Crave Creations"],
        name: "Mini Cakes",
        description: "Indulgent mini cake servings with layered toppings — banana, toasted marshmallow, graham cracker crumble, and chocolate sauce.",
        price: "$10",
        imageUrl: "/images/crave-mini-cakes.jpg",
        reservationAllowed: false,
        status: "live",
      },
      {
        vendorId: vendorMap["Crave Creations"],
        name: "Lemonades",
        description: "Fresh house-made lemonades in five flavors: Classic ($4), Strawberry, Lavender, Passion Fruit, or Peach Mango ($5 each). Add a lemonade to any food order for just $3 with the Crave Combo.",
        price: "$4–$5",
        imageUrl: "/images/crave-mocktails.jpg",
        reservationAllowed: false,
        status: "live",
      },
      // Spice Weasel Sauce
      {
        vendorId: vendorMap["Spice Weasel Sauce"],
        name: "Original Hot Sauce",
        description: "Made from handpicked, homegrown hot Portugal, dalle, and Thai chili peppers. Versatile on eggs, burgers, tacos, and more. Small batch, all natural.",
        price: "$10",
        imageUrl: "https://images.squarespace-cdn.com/content/v1/65c95b24057f5f371ef5e507/1715453602071-IAMHQT2E09VEE5ANYTX0/SpiceWeasel_HS-4.jpg",
        reservationAllowed: true,
        maxPerReservation: 4,
        quantityAvailable: 30,
        status: "live",
      },
      {
        vendorId: vendorMap["Spice Weasel Sauce"],
        name: "Golden Weasel",
        description: "Carolina Gold–inspired blend of sweet honey, mustard, and Spice Weasel's original hot sauce. Perfect as a dipping sauce or on sandwiches.",
        price: "$10",
        imageUrl: "https://images.squarespace-cdn.com/content/v1/65c95b24057f5f371ef5e507/1715453523062-80WLRD9XN3W5RC3YRTOJ/SpiceWeasel_HM-4.jpg",
        reservationAllowed: true,
        maxPerReservation: 4,
        quantityAvailable: 30,
        status: "live",
      },
      {
        vendorId: vendorMap["Spice Weasel Sauce"],
        name: "Momo Sauce",
        description: "Tomato-based hot sauce inspired by the momo sauces of Sikkim, India. Great on dumplings, crispy tenders, and anything that needs a kick.",
        price: "$10",
        imageUrl: "https://images.squarespace-cdn.com/content/v1/65c95b24057f5f371ef5e507/1715453454241-UDJ5S2VU5I7KKJ5G105G/SpiceWeasel_Momo-3.jpg",
        reservationAllowed: true,
        maxPerReservation: 4,
        quantityAvailable: 30,
        status: "live",
      },
      {
        vendorId: vendorMap["Spice Weasel Sauce"],
        name: "Dalle Salsa",
        description: "Chunky salsa built around the fiery dalle pepper — a rare round chili from the Sikkim region. Big heat, bold flavor.",
        price: "$10",
        imageUrl: "https://images.squarespace-cdn.com/content/v1/65c95b24057f5f371ef5e507/1715453555525-DY0L1VQ0NVS5RC8C2XEE/SpiceWeasel_Salsa-2.jpg",
        reservationAllowed: true,
        maxPerReservation: 4,
        quantityAvailable: 30,
        status: "live",
      },
      {
        vendorId: vendorMap["Spice Weasel Sauce"],
        name: "Hot Honey",
        description: "Local honey infused with Spice Weasel's signature hot peppers. Drizzle on pizza, fried chicken, cheese, or charcuterie.",
        price: "$12",
        imageUrl: "https://images.squarespace-cdn.com/content/v1/65c95b24057f5f371ef5e507/1748016400166-Q8IX1SMJDL1EFEJ2F0HD/5CCCA21E-5B1B-4B31-8EE1-DC444B83CE0E.jpeg",
        reservationAllowed: true,
        maxPerReservation: 4,
        quantityAvailable: 20,
        status: "live",
      },
      {
        vendorId: vendorMap["Spice Weasel Sauce"],
        name: "Spicy Seasoning Salt",
        description: "Handcrafted seasoning salt blended with Spice Weasel's signature hot peppers. Great on popcorn, grilled meats, eggs — anything that needs a boost.",
        price: "$10",
        imageUrl: "https://images.squarespace-cdn.com/content/v1/65c95b24057f5f371ef5e507/1748016170759-F74CMMQW5TSOUJ4G8PZI/274885A2-929E-4608-806D-489EE2B9F432.jpeg",
        reservationAllowed: true,
        maxPerReservation: 4,
        quantityAvailable: 20,
        status: "live",
      },
      {
        vendorId: vendorMap["Spice Weasel Sauce"],
        name: "Original Four Pack",
        description: "One of each — Original Hot Sauce, Dalle Salsa, Golden Weasel, and Momo Sauce. The complete Spice Weasel lineup at a bundle price.",
        price: "$36",
        imageUrl: "https://images.squarespace-cdn.com/content/v1/65c95b24057f5f371ef5e507/1721320057753-9T57TTP085A9BRTWHSCS/SpiceWeasel_All-1.png",
        reservationAllowed: true,
        maxPerReservation: 2,
        quantityAvailable: 15,
        status: "live",
      },
      // Riverdale Farm (reserve for pickup)
      {
        vendorId: vendorMap["Riverdale Farm"],
        name: "Strawberries",
        description: "Fresh-picked strawberries straight from the fields. Sweet, local, and in peak season.",
        price: "$7 / pint | $14 / quart",
        imageUrl: "/images/riverdale-strawberries.png",
        reservationAllowed: true,
        maxPerReservation: 2,
        quantityAvailable: 15,
        status: "live",
      },
      {
        vendorId: vendorMap["Riverdale Farm"],
        name: "Lettuce",
        description: "Crisp heads of lettuce grown fresh on the farm. Great for salads and sandwiches.",
        price: "$4 / head",
        imageUrl: "/images/riverdale-lettuce.png",
        reservationAllowed: true,
        maxPerReservation: 2,
        quantityAvailable: 25,
        status: "live",
      },
      {
        vendorId: vendorMap["Riverdale Farm"],
        name: "Sweet Peppers",
        description: "Colorful sweet peppers, harvested at peak ripeness. Great for roasting, stir-fries, or eating fresh.",
        price: "$3.50 / lb",
        reservationAllowed: true,
        maxPerReservation: 3,
        quantityAvailable: 20,
        status: "live",
      },
      {
        vendorId: vendorMap["Riverdale Farm"],
        name: "Eggplant",
        description: "Italian and globe eggplant grown on the farm. Perfect for grilling, roasting, or making eggplant parm.",
        price: "$3.50 / lb",
        reservationAllowed: true,
        maxPerReservation: 3,
        quantityAvailable: 20,
        status: "live",
      },
      {
        vendorId: vendorMap["Riverdale Farm"],
        name: "Broccoli",
        description: "Farm-fresh broccoli with tight, dark green florets. Harvested at peak tenderness.",
        price: "$3.50 / lb",
        imageUrl: "/images/riverdale-broccoli.png",
        reservationAllowed: true,
        maxPerReservation: 3,
        quantityAvailable: 20,
        status: "live",
      },
      {
        vendorId: vendorMap["Riverdale Farm"],
        name: "Cabbage",
        description: "Dense, fresh-cut cabbage heads from the farm. Great for slaws, stir-fries, and soups.",
        price: "$2.50 / lb",
        imageUrl: "/images/riverdale-cabbage.png",
        reservationAllowed: true,
        maxPerReservation: 3,
        quantityAvailable: 20,
        status: "live",
      },
      {
        vendorId: vendorMap["Riverdale Farm"],
        name: "Root Vegetables",
        description: "Seasonal mix of potatoes, beets, and carrots — sweet and earthy, fresh from the fields.",
        price: "$2.50 / lb",
        imageUrl: "/images/riverdale-root-veg.png",
        reservationAllowed: true,
        maxPerReservation: 3,
        quantityAvailable: 20,
        status: "live",
      },
      // Teresa's Farm (baked goods)
      {
        vendorId: vendorMap["Teresa's Farm"],
        name: "Artisan Jams (6oz)",
        description: "Small-batch jams in rotating flavors: strawberry kiwi, blueberry kiwi, triple berry, lemon pie, raspberry lemonade, key lime pie, strawberry rhubarb, pear & ginger, and more. Made from Teresa's kitchen.",
        price: "$8",
        imageUrl: "/images/teresa-jams.jpg",
        reservationAllowed: true,
        maxPerReservation: 4,
        quantityAvailable: 40,
        status: "live",
      },
      {
        vendorId: vendorMap["Teresa's Farm"],
        name: "Tarts (box of 4)",
        description: "Rich, hand-made tarts in your choice of flavor — triple berry, chocolate cream, banana cream, coconut cream, vanilla cream, summer berry, or lemon meringue. Four per box.",
        price: "$6",
        imageUrl: "/images/teresa-tarts.jpg",
        reservationAllowed: true,
        maxPerReservation: 4,
        quantityAvailable: 30,
        status: "live",
      },
      {
        vendorId: vendorMap["Teresa's Farm"],
        name: "Braided Loaf",
        description: "Artisan braided breads in rotating varieties: sesame honey, olive, rosemary garlic, almond, pistachio, sun-dried tomato, chive & garlic, and baguettes.",
        price: "$12",
        imageUrl: "/images/teresa-braided-loaf.jpg",
        reservationAllowed: true,
        maxPerReservation: 2,
        quantityAvailable: 20,
        status: "live",
      },
      {
        vendorId: vendorMap["Teresa's Farm"],
        name: "Danish",
        description: "Handmade Danish pastries in unique flavors — cheese, almond, blueberry, raspberry, berry, cinnamon, and lemon. Baked fresh for each market.",
        price: "$4",
        imageUrl: "/images/teresa-danish.jpg",
        reservationAllowed: true,
        maxPerReservation: 6,
        quantityAvailable: 40,
        status: "live",
      },
      {
        vendorId: vendorMap["Teresa's Farm"],
        name: "Specialty Focaccia Bread",
        description: "Thick, pillowy focaccia in savory and sweet varieties: vegetable, herb, rosemary garlic butter, blueberry strawberry, and garlic & chive butter.",
        price: "$15",
        reservationAllowed: true,
        maxPerReservation: 2,
        quantityAvailable: 15,
        status: "live",
      },
    ])
    .returning();

  console.log(`Inserted ${products.length} products.`);
  console.log("Seed complete.");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
